# CI  de NÍVEL 1 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execução manual'

# regras de execução (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch

on:
  workflow_dispatch: 

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

    # maquina que o job vai executar
    runs-on: ubuntu-latest

    #passos do script de build
    steps:
         - uses: actions/checkout@v4
         - name: Use Node.js
           uses: actions/setup-node@v4
           with:
             node-version: '22.x'
         - name: Install dependencies
           run: npm ci
         - name: Run Mocha tests
           run: npm test
         - name: Publish Test Summary Results
           if: always()
           uses: actions/upload-artifact@v4
           with:
             name: test-results
             path: test_results.json
      
